services:
  api:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app   
    command: uv run fastapi dev --host 0.0.0.0 --port 8000
    depends_on:
      - redis
  # api2:
  #   build: .
  #   env_file: .env
  #   ports:
  #     - "8001:8000"
  #   volumes:
  #     - ./app:/app/app
  #   command: uv run fastapi dev --host 0.0.0.0 --port 8000
  #   depends_on:
  #     - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  redis_gui:
    image: redis/redisinsight
    ports:
      - 5540:5540